services:
  - type: web
    name: stormtrace-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: OWM_KEY
        sync: false
      - key: MAPBOX_TOKEN
        sync: false
