import React from 'react';
import { BookOpen, Cpu, ShieldAlert, Sparkles, Map, Info } from 'lucide-react';

export const HowItWorks: React.FC = () => {
  return (
    <div className="space-y-6 pb-12">
      <div className="glass-panel p-6 rounded-2xl border border-slate-800 space-y-4">
        <div className="flex items-center gap-3 mb-2">
          <BookOpen className="h-8 w-8 text-cyan-400" />
          <div>
            <h2 className="text-2xl font-black text-slate-100">How It Works: SIH26078 Guide</h2>
            <p className="text-sm text-slate-400">Documentation on the architecture, workflows, and modules of StormTrace AI.</p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="glass-panel p-6 rounded-xl border border-slate-800 space-y-4">
          <h3 className="text-lg font-bold text-slate-100 flex items-center gap-2 border-b border-slate-800 pb-2">
            <Cpu className="h-5 w-5 text-emerald-400" />
            1. Core AI Architecture
          </h3>
          <ul className="space-y-3 text-sm text-slate-300">
            <li>
              <strong className="text-cyan-300 block">Spherical Icosahedral GNN (Stage 1)</strong>
              Detects extreme weather anomalies (Cyclones, Heatwaves, Coldwaves) on a spherical mesh to avoid 2D distortions, creating 4D Anomaly Bounding Boxes (4D-ABBs).
            </li>
            <li>
              <strong className="text-cyan-300 block">Conditional DDPM Downscaling (Stage 2)</strong>
              Downscales 12 km coarse NWP forecasts to 5 km/1 km resolution while strictly preserving PSD (Power Spectral Density). This avoids the spectral smoothing common in old U-Net models.
            </li>
          </ul>
        </div>

        <div className="glass-panel p-6 rounded-xl border border-slate-800 space-y-4">
          <h3 className="text-lg font-bold text-slate-100 flex items-center gap-2 border-b border-slate-800 pb-2">
            <Sparkles className="h-5 w-5 text-blue-400" />
            2. Gen AI & Agentic Workflows
          </h3>
          <ul className="space-y-3 text-sm text-slate-300">
            <li>
              <strong className="text-cyan-300 block">Gen AI Incident Copilot</strong>
              Located in the <span className="font-mono bg-slate-900 px-1 rounded">4D Anomaly Tracking</span> tab. A generative LLM analyzes the current threat parameters and auto-generates a detailed incident report.
            </li>
            <li>
              <strong className="text-cyan-300 block">Agentic Resource Dispatch</strong>
              An autonomous AI agent negotiates SDRF team availability and triggers autonomous dispatch of disaster management resources to affected tehsils.
            </li>
          </ul>
        </div>

        <div className="glass-panel p-6 rounded-xl border border-slate-800 space-y-4">
          <h3 className="text-lg font-bold text-slate-100 flex items-center gap-2 border-b border-slate-800 pb-2">
            <Map className="h-5 w-5 text-amber-400" />
            3. 3D GIS Radar & Live Tracking
          </h3>
          <ul className="space-y-3 text-sm text-slate-300">
            <li>
              <strong className="text-cyan-300 block">Pan-India Coverage</strong>
              Supports real-time mapping of extreme rainfall, heat domes, cyclones, and wind extremes.
            </li>
            <li>
              <strong className="text-cyan-300 block">Interactive Globe</strong>
              Use the <span className="font-mono bg-slate-900 px-1 rounded">Weather Map</span> tab to view the DDPM-generated 5 km risk grid and extreme probability contours.
            </li>
          </ul>
        </div>

        <div className="glass-panel p-6 rounded-xl border border-slate-800 space-y-4">
          <h3 className="text-lg font-bold text-slate-100 flex items-center gap-2 border-b border-slate-800 pb-2">
            <ShieldAlert className="h-5 w-5 text-red-400" />
            4. Real-time Alerts & Bulletins
          </h3>
          <ul className="space-y-3 text-sm text-slate-300">
            <li>
              <strong className="text-cyan-300 block">Active Dispatch Center</strong>
              The <span className="font-mono bg-slate-900 px-1 rounded">Risk & Alerts</span> tab aggregates multi-hazard alerts generated by the system and provides one-click PDF/CSV exports for disaster authorities.
            </li>
          </ul>
        </div>
        
        <div className="glass-panel p-6 rounded-xl border border-slate-800 space-y-4 md:col-span-2">
          <h3 className="text-lg font-bold text-slate-100 flex items-center gap-2 border-b border-slate-800 pb-2">
            <Info className="h-5 w-5 text-purple-400" />
            5. Map Legend & Symbol Glossary
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 text-sm text-slate-300">
            <div className="flex items-start gap-3 bg-slate-900/50 p-3 rounded-lg border border-slate-800">
              <div className="w-4 h-4 rounded-full bg-red-500 animate-pulse shrink-0 mt-0.5 shadow-[0_0_10px_rgba(239,68,68,0.8)]"></div>
              <div>
                <strong className="text-red-400 block text-xs">Critical Threat Centroid</strong>
                <span className="text-[11px]">Marks the center of a severe weather anomaly (e.g., Eye of Cyclone).</span>
              </div>
            </div>
            
            <div className="flex items-start gap-3 bg-slate-900/50 p-3 rounded-lg border border-slate-800">
              <div className="w-8 h-4 border-t-2 border-dashed border-cyan-400 shrink-0 mt-1"></div>
              <div>
                <strong className="text-cyan-400 block text-xs">GNN Trajectory Track</strong>
                <span className="text-[11px]">Dashed line predicting the future path of the 4D anomaly.</span>
              </div>
            </div>
            
            <div className="flex items-start gap-3 bg-slate-900/50 p-3 rounded-lg border border-slate-800">
              <div className="w-6 h-6 border-2 border-red-500 bg-red-500/20 rounded shrink-0"></div>
              <div>
                <strong className="text-red-300 block text-xs">4D Anomaly Bounding Box</strong>
                <span className="text-[11px]">The geographical area impacted by the extreme event.</span>
              </div>
            </div>

            <div className="flex items-start gap-3 bg-slate-900/50 p-3 rounded-lg border border-slate-800">
              <div className="w-4 h-4 rounded bg-amber-500 shrink-0 mt-0.5"></div>
              <div>
                <strong className="text-amber-400 block text-xs">Moderate / Severe Risk (Orange)</strong>
                <span className="text-[11px]">Indicates areas with a high probability of severe weather.</span>
              </div>
            </div>

            <div className="flex items-start gap-3 bg-slate-900/50 p-3 rounded-lg border border-slate-800">
              <div className="w-4 h-4 rounded-full bg-cyan-500/50 border border-cyan-400 shrink-0 mt-0.5"></div>
              <div>
                <strong className="text-cyan-300 block text-xs">5km Risk Grid Cell</strong>
                <span className="text-[11px]">Hover over these squares on the map to see local precipitation/temperature.</span>
              </div>
            </div>
            
            <div className="flex items-start gap-3 bg-slate-900/50 p-3 rounded-lg border border-slate-800">
              <div className="w-5 h-5 bg-emerald-950 border border-emerald-800 rounded flex items-center justify-center shrink-0">
                <span className="text-[10px]">🤖</span>
              </div>
              <div>
                <strong className="text-emerald-400 block text-xs">Agentic / Gen AI Badges</strong>
                <span className="text-[11px]">Indicates modules powered by autonomous LLM workflows.</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
