import type { AlertItem, ThreatObject } from '../types/weather';

export function exportToCSV(filename: string, rows: object[]) {
  if (!rows || !rows.length) return;
  const headers = Object.keys(rows[0]);
  const csvContent = [
    headers.join(','),
    ...rows.map(row => 
      headers.map(header => {
        const val = (row as Record<string, unknown>)[header];
        const stringified = typeof val === 'object' ? JSON.stringify(val) : String(val);
        // Escape quotes
        return `"${stringified.replace(/"/g, '""')}"`;
      }).join(',')
    )
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function generateEventReportPDF(threat: ThreatObject) {
  const reportText = `
================================================================================
                       ASTRAWATCH AI - DISASTER INCIDENT REPORT
================================================================================
EVENT ID: ${threat.id}
EVENT NAME: ${threat.name}
DISTRICT: ${threat.district} (${threat.region})
SEVERITY LEVEL: ${threat.riskLevel.toUpperCase()}
TIMESTAMP: ${threat.timestamp}
FORECAST STEP: ${threat.forecastStep}

--- HYDROMETEOROLOGICAL PARAMETERS ---
Centroid Coordinates: Lat ${threat.centroid[0]}°N, Lng ${threat.centroid[1]}°E
Bounding Box Area: ${threat.areaKm2} sq km
Peak Rainfall Intensity: ${threat.peakIntensityMmH} mm/hr
Extreme Forecast Index (EFI) Score: ${threat.efiScore}
Exceedance Probability (>50mm): ${threat.probabilityExceedance}%
Trajectory Track Speed: ${threat.speedKmH} km/h towards ${threat.direction}

--- IMPACTED GEOGRAPHY & POPULATION ---
Estimated Affected Population: ${threat.affectedPopulationEstimate.toLocaleString()} citizens
Impacted Tehsils / Villages:
${threat.affectedVillages.map(v => ` - ${v}`).join('\n')}

--- OFFICIAL ADVISORY & DISASTER RESPONSE ---
${threat.advisory}

--- AI DOWNSCALING & PREDICTIVE METRICS ---
Model Architecture: AstraWatch 5 km Conditional Diffusion & Anomaly Tracker
Preserved Peak Intensity Error: < 4.2%
Grid Resolution: 5.0 km downscaled grid conditioned on DEM elevation & moisture flux

================================================================================
Generated automatically by AstraWatch AI Decision-Support Platform for SIH 2026.
Official Meteorological Warnings take precedence.
================================================================================
  `.trim();

  const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${threat.id}_Incident_Report.txt`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function generateAlertSummaryPDF(alerts: AlertItem[]) {
  const alertText = `
================================================================================
                     ASTRAWATCH AI - ACTIVE ALERTS BULLETIN
================================================================================
Issued At: ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST
Total Active Alerts: ${alerts.length}

${alerts.map(a => `
[${a.riskLevel.toUpperCase()}] ${a.id}: ${a.title}
District: ${a.district} | Issued: ${a.issuedAt} | Valid Until: ${a.validUntil}
Tehsils: ${a.affectedTehsils.join(', ')}
Summary: ${a.summary}
Actions:
${a.recommendedActions.map(act => `  * ${act}`).join('\n')}
--------------------------------------------------------------------------------
`).join('\n')}

Generated by AstraWatch AI | Uttar Pradesh Meteorological Intelligence Node
  `.trim();

  const blob = new Blob([alertText], { type: 'text/plain;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `AstraWatch_Active_Alerts_${Date.now()}.txt`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
